### ISSUE TITLE
Error in 3 outputs

### ISSUE THREAD

**Issue by gonzaurv** [patonlab/GoodVibes#61]
Dear,
I am doing the goodvibes correction to a diagram of energies, using the comands " -t 368.15 and -c 1". Is working perfectly with my data, but i don't know why, the program doesn't work with 3 outputs. I check the input of this files and is the same that the others, so there is not a problem in my input, but even this the goodvibes don't work. Take into account, that i did the goodvibes calculation for other 40 files and there all work perfectly, but with this 3 outputs there is a particular problem, that i cannot find. Following i send the error that come out with this files:

   Requested:

   Temperature = 298.15 Kelvin   Pressure = 1 atm
   All energetic values below shown in Hartree unless otherwise specified.Traceback (most recent call last):
  File "/home/programes/conda/miniconda3/envs/goodvibes/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/programes/conda/miniconda3/envs/goodvibes/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/programes/conda/miniconda3/envs/goodvibes/lib/python3.7/site-packages/goodvibes/__main__.py", line 18, in <module>
    sys.exit(GoodVibes.main())
  File "/home/programes/conda/miniconda3/envs/goodvibes/lib/python3.7/site-packages/goodvibes/GoodVibes.py", line 2468, in main
    lot_sm_prog = read_initial(file)
  File "/home/programes/conda/miniconda3/envs/goodvibes/lib/python3.7/site-packages/goodvibes/GoodVibes.py", line 1583, in read_initial
    with open(file) as f: data = f.readlines()
  File "/home/programes/conda/miniconda3/envs/goodvibes/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
**UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 4830: invalid continuation byte**

It would be really helpfull for my work if someone can help me with this. Thanks you for your attention.

Regards.

Gonzalo Nuñez
Tarragona, Spain

**Comment by luchini18** [comment]
Hi @gonzaurv,
Difficult to say what is going on here looking at this output. Can you tell me what version of GoodVibes you have installed? It should print it at the top of your GoodVibes output. 
It also might help if I could see the output files, could you upload the three problem output files here or email them to me at guilian.luchini@colostate.edu if you are comfortable? 
Thanks.
