### ISSUE TITLE
Could not parse Gaussian output file for constrained geometry optimisation correctly 

### ISSUE THREAD

**Issue by xinglong-zhang** [patonlab/GoodVibes#72]
While trying to use goodvibes to parse the thermochemistry data from Gaussian output file for constrained geometry optimisation, the following error arises:

> Error output: [Gaussian TS_5coord_L2_subst_opt.log ERROR] Encountered error when parsing.
> [Gaussian TS_5coord_L2_subst_opt.log ERROR] Last line read:                       A                      A                      A
> 
> Traceback (most recent call last):
>   File "/Users/xinglongzhang/miniconda3/envs/pyatoms-dev/bin/goodvibes", line 8, in <module>
>     sys.exit(main())
>   File "/Users/xinglongzhang/miniconda3/envs/pyatoms-dev/lib/python3.10/site-packages/goodvibes/GoodVibes.py", line 1038, in main
>     bbe = calc_bbe(file, options.QS, options.QH, options.S_freq_cutoff, options.H_freq_cutoff, options.temperature,
>   File "/Users/xinglongzhang/miniconda3/envs/pyatoms-dev/lib/python3.10/site-packages/goodvibes/thermo.py", line 409, in __init__
>     self.xyz = getoutData(file)
>   File "/Users/xinglongzhang/miniconda3/envs/pyatoms-dev/lib/python3.10/site-packages/goodvibes/io.py", line 99, in __init__
>     data = ccread(filename)
>   File "/Users/xinglongzhang/miniconda3/envs/pyatoms-dev/lib/python3.10/site-packages/cclib/io/ccio.py", line 188, in ccread
>     return log.parse()
>   File "/Users/xinglongzhang/miniconda3/envs/pyatoms-dev/lib/python3.10/site-packages/cclib/parser/logfileparser.py", line 171, in parse
>     self.extract(self.inputfile, line)
>   File "/Users/xinglongzhang/miniconda3/envs/pyatoms-dev/lib/python3.10/site-packages/cclib/parser/gaussianparser.py", line 1476, in extract
>     numbers = [float(s) for s in line[10:].split()]
>   File "/Users/xinglongzhang/miniconda3/envs/pyatoms-dev/lib/python3.10/site-packages/cclib/parser/gaussianparser.py", line 1476, in <listcomp>
>     numbers = [float(s) for s in line[10:].split()]
> ValueError: could not convert string to float: 'A'

The output file is attached.
[test.log](https://github.com/patonlab/GoodVibes/files/14151903/test.log)

**Comment by dosshubha** [comment]
You can try to run the constrained optimization using the opt=modredundant in the route section and then freezing the atoms in the section following the geometry specifications. This might solve the parsing issue!

**Comment by bobbypaton** [comment]
fixed now
