### ISSUE TITLE
Stereoselectivity calculations

### ISSUE THREAD

**Issue by SimoneGallarati** [patonlab/GoodVibes#74]
I have been trying to reproduce Example 10 (Stereoselectivity and Boltzmann populations) using the data provided in goodvibes/examples/gconf_ee_boltz. I get the following error when trying to read the --ee "*_R*:*_S*" argument: 

Traceback (most recent call last):
  File "/Users/simonegallarati/psi4conda/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/simonegallarati/psi4conda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/simonegallarati/GoodVibes-master/goodvibes/__main__.py", line 18, in <module>
    sys.exit(GoodVibes.main())
  File "/Users/simonegallarati/GoodVibes-master/goodvibes/GoodVibes.py", line 3589, in main
    options.temperature, log, dup_list)
  File "/Users/simonegallarati/GoodVibes-master/goodvibes/GoodVibes.py", line 2074, in get_selectivity
    B = ''.join(b for b in pattern[1] if b.isalnum())
IndexError: list index out of range

I have tried with different versions of Goodvibes (including the latest) and different test files, but never managed to get this argument to work.
Any ideas about this?

**Comment by bobbypaton** [comment]
fixed!
